#ifndef MODEL_DPOWER_STREAMLINE
#define MODEL_DPOWER_STREAMLINE

#define DPOWER_STREAMLINE                       1
#define DPOWER_STREAMLINE_HOEHE_MIN            -90
#define DPOWER_STREAMLINE_HOEHE_MAX             90
#define DPOWER_STREAMLINE_SEITE_MIN            -65
#define DPOWER_STREAMLINE_SEITE_MAX             65
#define DPOWER_STREAMLINE_QUER_MIN             -30
#define DPOWER_STREAMLINE_QUER_MAX              100
#define DPOWER_STREAMLINE_MOTOR_MIN             0
#define DPOWER_STREAMLINE_MOTOR_MAX             100
#define DPOWER_STREAMLINE_FLIP_HOEHE           -1
#define DPOWER_STREAMLINE_FLIP_SEITE            1
#define DPOWER_STREAMLINE_FLIP_QUER_LINKS      -1
#define DPOWER_STREAMLINE_FLIP_QUER_RECHTS     -1
#define DPOWER_STREAMLINE_FLIP_FLAP_LINKS       1
#define DPOWER_STREAMLINE_FLIP_FLAP_RECHTS      1
#define DPOWER_STREAMLINE_BUTTERFLY             65
#define DPOWER_STREAMLINE_EXPO_QUER             512
#define DPOWER_STREAMLINE_EXPO_HOEHE            512
#define DPOWER_STREAMLINE_EXPO_SEITE            128
#define DPOWER_STREAMLINE_QUER_SEITE_MISCHER    25
#define DPOWER_STREAMLINE_QUER_FLAPS_MISCHER    0
#define DPOWER_STREAMLINE_FLAP_HOEHE_MISCHER    0
#define DPOWER_STREAMLINE_MOTR_HOEHE_MISCHER    3
#define DPOWER_STREAMLINE_MOTR_HOEHE_TOTZONE    500

#endif