#ifndef MODEL_GRAUPNER_AMIGO4
#define MODEL_GRAUPNER_AMIGO4

#define GRAUPNER_AMIGO4                       1
#define GRAUPNER_AMIGO4_HOEHE_MIN            -100
#define GRAUPNER_AMIGO4_HOEHE_MAX             100
#define GRAUPNER_AMIGO4_SEITE_MIN            -100
#define GRAUPNER_AMIGO4_SEITE_MAX             100
#define GRAUPNER_AMIGO4_QUER_MIN             -100
#define GRAUPNER_AMIGO4_QUER_MAX              100
#define GRAUPNER_AMIGO4_MOTOR_MIN             0
#define GRAUPNER_AMIGO4_MOTOR_MAX             100
#define GRAUPNER_AMIGO4_FLIP_HOEHE           -1
#define GRAUPNER_AMIGO4_FLIP_SEITE           -1
#define GRAUPNER_AMIGO4_FLIP_QUER            -1
#define GRAUPNER_AMIGO4_BUTTERFLY             0
#define GRAUPNER_AMIGO4_EXPO_QUER             512
#define GRAUPNER_AMIGO4_EXPO_HOEHE            512
#define GRAUPNER_AMIGO4_EXPO_SEITE            128
#define GRAUPNER_AMIGO4_QUER_SEITE_MISCHER    50
#define GRAUPNER_AMIGO4_QUER_FLAPS_MISCHER    0
#define GRAUPNER_AMIGO4_FLAP_HOEHE_MISCHER    0
#define GRAUPNER_AMIGO4_MOTR_HOEHE_MISCHER    30

#endif