#ifndef MODEL_MULTIPLEX_HERON
#define MODEL_MULTIPLEX_HERON

#define MULTIPLEX_HERON                       0
#define MULTIPLEX_HERON_HOEHE_MIN            -60
#define MULTIPLEX_HERON_HOEHE_MAX             60
#define MULTIPLEX_HERON_SEITE_MIN            -100
#define MULTIPLEX_HERON_SEITE_MAX             100
#define MULTIPLEX_HERON_QUER_MIN             -50
#define MULTIPLEX_HERON_QUER_MAX              85
#define MULTIPLEX_HERON_MOTOR_MIN             0
#define MULTIPLEX_HERON_MOTOR_MAX             70
#define MULTIPLEX_HERON_FLIP_HOEHE            1
#define MULTIPLEX_HERON_FLIP_SEITE            1
#define MULTIPLEX_HERON_FLIP_QUER_LINKS      -1
#define MULTIPLEX_HERON_FLIP_QUER_RECHTS     -1
#define MULTIPLEX_HERON_FLIP_FLAP_LINKS       1
#define MULTIPLEX_HERON_FLIP_FLAP_RECHTS      1
#define MULTIPLEX_HERON_BUTTERFLY             100
#define MULTIPLEX_HERON_EXPO_QUER             512
#define MULTIPLEX_HERON_EXPO_HOEHE            512
#define MULTIPLEX_HERON_EXPO_SEITE            128
#define MULTIPLEX_HERON_QUER_SEITE_MISCHER    25
#define MULTIPLEX_HERON_QUER_FLAPS_MISCHER    50
#define MULTIPLEX_HERON_FLAP_HOEHE_MISCHER    0
#define MULTIPLEX_HERON_MOTR_HOEHE_MISCHER    3
#define MULTIPLEX_HERON_MOTR_HOEHE_TOTZONE    500

#endif