#ifndef MODEL_MULTIPLEX_EASYGLIDER
#define MODEL_MULTIPLEX_EASYGLIDER

#define MULTIPLEX_EASYGLIDER                       2
#define MULTIPLEX_EASYGLIDER_HOEHE_MIN            -100
#define MULTIPLEX_EASYGLIDER_HOEHE_MAX             100
#define MULTIPLEX_EASYGLIDER_SEITE_MIN            -85
#define MULTIPLEX_EASYGLIDER_SEITE_MAX             85
#define MULTIPLEX_EASYGLIDER_QUER_MIN             -100
#define MULTIPLEX_EASYGLIDER_QUER_MAX              100
#define MULTIPLEX_EASYGLIDER_MOTOR_MIN             0
#define MULTIPLEX_EASYGLIDER_MOTOR_MAX             100
#define MULTIPLEX_EASYGLIDER_FLIP_HOEHE            1
#define MULTIPLEX_EASYGLIDER_FLIP_SEITE            1
#define MULTIPLEX_EASYGLIDER_FLIP_QUER_LINKS       1
#define MULTIPLEX_EASYGLIDER_FLIP_QUER_RECHTS      1
#define MULTIPLEX_EASYGLIDER_FLIP_FLAP_LINKS       1
#define MULTIPLEX_EASYGLIDER_FLIP_FLAP_RECHTS      1
#define MULTIPLEX_EASYGLIDER_BUTTERFLY             100
#define MULTIPLEX_EASYGLIDER_EXPO_QUER             512
#define MULTIPLEX_EASYGLIDER_EXPO_HOEHE            512
#define MULTIPLEX_EASYGLIDER_EXPO_SEITE            128
#define MULTIPLEX_EASYGLIDER_QUER_SEITE_MISCHER    25
#define MULTIPLEX_EASYGLIDER_QUER_FLAPS_MISCHER    50
#define MULTIPLEX_EASYGLIDER_FLAP_HOEHE_MISCHER    0
#define MULTIPLEX_EASYGLIDER_MOTR_HOEHE_MISCHER    0
#define MULTIPLEX_EASYGLIDER_MOTR_HOEHE_TOTZONE    600

#endif